---
#hetzner_token: ""
cluster_name: "remindle-k8s"
kubeconfig_path: "/cluster/.kubeconfig"
k3s_version: v1.22.3+k3s1
public_ssh_key_path: "~/.ssh/id_ed25519.pub"
private_ssh_key_path: "~/.ssh/id_ed25519"
ssh_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
location: nbg1
schedule_workloads_on_masters: false
masters:
  instance_type: cpx11
  instance_count: 1
worker_node_pools:
- name: small
  instance_type: cx21
  instance_count: 1
